// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.Repositories;

namespace Model.Migrations
{
    [DbContext(typeof(EFOpleidingenContext))]
    [Migration("20200625095128_Weddeverhoging docent 1")]
    partial class Weddeverhogingdocent1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.5.20278.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Entities.Campus", b =>
                {
                    b.Property<int>("CampusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Gemeente")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Huisnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnName("CampusNaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Straat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CampusId");

                    b.ToTable("Campussen");

                    b.HasData(
                        new
                        {
                            CampusId = 1,
                            Gemeente = "Antwerpen",
                            Huisnummer = "22",
                            Naam = "Andros",
                            Postcode = "2018",
                            Straat = "Somersstraat"
                        },
                        new
                        {
                            CampusId = 2,
                            Gemeente = "Dendermonde",
                            Huisnummer = "17",
                            Naam = "Delos",
                            Postcode = "9200",
                            Straat = "Oude Vest"
                        },
                        new
                        {
                            CampusId = 3,
                            Gemeente = "Genk",
                            Huisnummer = "37",
                            Naam = "Gavdos",
                            Postcode = "3600",
                            Straat = "Europalaan"
                        },
                        new
                        {
                            CampusId = 4,
                            Gemeente = "Heverlee",
                            Huisnummer = "2",
                            Naam = "Hydra",
                            Postcode = "3001",
                            Straat = "Interleuvenlaan"
                        },
                        new
                        {
                            CampusId = 5,
                            Gemeente = "Wevelgem",
                            Huisnummer = "10",
                            Naam = "Ikaria",
                            Postcode = "8560",
                            Straat = "Vlamingstraat"
                        },
                        new
                        {
                            CampusId = 6,
                            Gemeente = "Oostende",
                            Huisnummer = "4",
                            Naam = "Oinouses",
                            Postcode = "8400",
                            Straat = "Archimedesstraat"
                        });
                });

            modelBuilder.Entity("Model.Entities.Docent", b =>
                {
                    b.Property<int>("DocentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CampusId")
                        .HasColumnType("int");

                    b.Property<string>("Familienaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<bool?>("HeeftRijbewijs")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InDienst")
                        .HasColumnType("date");

                    b.Property<string>("LandCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal>("Wedde")
                        .HasColumnName("Maandwedde")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("DocentId");

                    b.HasIndex("CampusId");

                    b.HasIndex("LandCode");

                    b.ToTable("Docenten");

                    b.HasData(
                        new
                        {
                            DocentId = 1,
                            CampusId = 4,
                            Familienaam = "Abbeloos",
                            InDienst = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Willy",
                            Wedde = 1500m
                        },
                        new
                        {
                            DocentId = 2,
                            CampusId = 2,
                            Familienaam = "Abelshausen",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Joseph",
                            Wedde = 1800m
                        },
                        new
                        {
                            DocentId = 3,
                            CampusId = 3,
                            Familienaam = "Achten",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Joseph",
                            Wedde = 1300m
                        },
                        new
                        {
                            DocentId = 4,
                            CampusId = 4,
                            Familienaam = "Adam",
                            InDienst = new DateTime(2019, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "François",
                            Wedde = 1700m
                        },
                        new
                        {
                            DocentId = 5,
                            CampusId = 1,
                            Familienaam = "Adriaensens",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Jan",
                            Wedde = 2100m
                        },
                        new
                        {
                            DocentId = 6,
                            CampusId = 6,
                            Familienaam = "Adriaensens",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "René",
                            Wedde = 1600m
                        },
                        new
                        {
                            DocentId = 7,
                            CampusId = 3,
                            Familienaam = "Aerenhouts",
                            InDienst = new DateTime(2019, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Frans",
                            Wedde = 1300m
                        },
                        new
                        {
                            DocentId = 8,
                            CampusId = 1,
                            Familienaam = "Aerts",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Emile",
                            Wedde = 1700m
                        },
                        new
                        {
                            DocentId = 9,
                            CampusId = 2,
                            Familienaam = "Aerts",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Jean",
                            Wedde = 1200m
                        },
                        new
                        {
                            DocentId = 10,
                            CampusId = 6,
                            Familienaam = "Aerts",
                            InDienst = new DateTime(2019, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Mario",
                            Wedde = 1600m
                        },
                        new
                        {
                            DocentId = 11,
                            CampusId = 5,
                            Familienaam = "Aerts",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Paul",
                            Wedde = 2000m
                        },
                        new
                        {
                            DocentId = 12,
                            CampusId = 5,
                            Familienaam = "Aerts",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Stefan",
                            Wedde = 1500m
                        },
                        new
                        {
                            DocentId = 13,
                            CampusId = 3,
                            Familienaam = "Alexander",
                            InDienst = new DateTime(2019, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "François",
                            Wedde = 1900m
                        },
                        new
                        {
                            DocentId = 14,
                            CampusId = 6,
                            Familienaam = " Allard",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Henri",
                            Wedde = 1600m
                        },
                        new
                        {
                            DocentId = 15,
                            CampusId = 1,
                            Familienaam = "Anciaux",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Albert",
                            Wedde = 1100m
                        },
                        new
                        {
                            DocentId = 16,
                            CampusId = 5,
                            Familienaam = "Anseeuw",
                            InDienst = new DateTime(2019, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Urbain",
                            Wedde = 1500m
                        },
                        new
                        {
                            DocentId = 17,
                            CampusId = 3,
                            Familienaam = "Antheunis",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Etienne",
                            Wedde = 1900m
                        },
                        new
                        {
                            DocentId = 18,
                            CampusId = 4,
                            Familienaam = "Arlet",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Jacques",
                            Wedde = 1400m
                        },
                        new
                        {
                            DocentId = 19,
                            CampusId = 2,
                            Familienaam = "Arras",
                            InDienst = new DateTime(2019, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Wim",
                            Wedde = 1800m
                        },
                        new
                        {
                            DocentId = 20,
                            CampusId = 2,
                            Familienaam = "Baens",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Roger",
                            Wedde = 2200m
                        },
                        new
                        {
                            DocentId = 21,
                            CampusId = 5,
                            Familienaam = "Baert",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Dirk",
                            Wedde = 1000m
                        },
                        new
                        {
                            DocentId = 22,
                            CampusId = 4,
                            Familienaam = "Baert",
                            InDienst = new DateTime(2019, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Hubert",
                            Wedde = 1400m
                        },
                        new
                        {
                            DocentId = 23,
                            CampusId = 2,
                            Familienaam = "Baert",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Jean-Pierre",
                            Wedde = 1800m
                        },
                        new
                        {
                            DocentId = 24,
                            CampusId = 3,
                            Familienaam = "Baeyens",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Armand",
                            Wedde = 1300m
                        },
                        new
                        {
                            DocentId = 25,
                            CampusId = 1,
                            Familienaam = "Baeyens",
                            InDienst = new DateTime(2019, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Jan",
                            Wedde = 1700m
                        },
                        new
                        {
                            DocentId = 26,
                            CampusId = 1,
                            Familienaam = "Baguet",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Roger",
                            Wedde = 2100m
                        },
                        new
                        {
                            DocentId = 27,
                            CampusId = 6,
                            Familienaam = "Baguet",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Serge",
                            Wedde = 1600m
                        },
                        new
                        {
                            DocentId = 28,
                            CampusId = 3,
                            Familienaam = "Balducq",
                            InDienst = new DateTime(2019, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Gérard",
                            Wedde = 1300m
                        },
                        new
                        {
                            DocentId = 29,
                            CampusId = 1,
                            Familienaam = "Barbé",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Koen",
                            Wedde = 1700m
                        },
                        new
                        {
                            DocentId = 30,
                            CampusId = 2,
                            Familienaam = "Barras",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Georges",
                            Wedde = 1200m
                        },
                        new
                        {
                            DocentId = 31,
                            CampusId = 6,
                            Familienaam = "Baumans",
                            InDienst = new DateTime(2019, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Auguste",
                            Wedde = 1600m
                        },
                        new
                        {
                            DocentId = 32,
                            CampusId = 5,
                            Familienaam = "Bauwens",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Arsène",
                            Wedde = 2000m
                        },
                        new
                        {
                            DocentId = 33,
                            CampusId = 5,
                            Familienaam = "Bauwens",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Henri",
                            Wedde = 1500m
                        },
                        new
                        {
                            DocentId = 34,
                            CampusId = 3,
                            Familienaam = "Bayens",
                            InDienst = new DateTime(2019, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Jules",
                            Wedde = 1900m
                        },
                        new
                        {
                            DocentId = 35,
                            CampusId = 6,
                            Familienaam = "Beckaert",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Albert",
                            Wedde = 1600m
                        },
                        new
                        {
                            DocentId = 36,
                            CampusId = 1,
                            Familienaam = "Beckaert",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Marcel",
                            Wedde = 1100m
                        },
                        new
                        {
                            DocentId = 37,
                            CampusId = 5,
                            Familienaam = "Beeckman",
                            InDienst = new DateTime(2019, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Koen",
                            Wedde = 1500m
                        },
                        new
                        {
                            DocentId = 38,
                            CampusId = 3,
                            Familienaam = "Beeckman",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Kamiel",
                            Wedde = 1900m
                        },
                        new
                        {
                            DocentId = 39,
                            CampusId = 4,
                            Familienaam = "Beeckman",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Theophile",
                            Wedde = 1400m
                        },
                        new
                        {
                            DocentId = 40,
                            CampusId = 2,
                            Familienaam = "Beheyt",
                            InDienst = new DateTime(2019, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Benoni",
                            Wedde = 1800m
                        },
                        new
                        {
                            DocentId = 41,
                            CampusId = 2,
                            Familienaam = "Beirnaert",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Albert",
                            Wedde = 2200m
                        },
                        new
                        {
                            DocentId = 42,
                            CampusId = 5,
                            Familienaam = "Belvaux",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Jean",
                            Wedde = 1000m
                        },
                        new
                        {
                            DocentId = 43,
                            CampusId = 4,
                            Familienaam = "Benoit",
                            InDienst = new DateTime(2019, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Adelin",
                            Wedde = 1400m
                        },
                        new
                        {
                            DocentId = 44,
                            CampusId = 2,
                            Familienaam = "Benoit",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Auguste",
                            Wedde = 1800m
                        },
                        new
                        {
                            DocentId = 45,
                            CampusId = 3,
                            Familienaam = "Berben",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Jef",
                            Wedde = 1300m
                        },
                        new
                        {
                            DocentId = 46,
                            CampusId = 1,
                            Familienaam = "Berckmans",
                            InDienst = new DateTime(2019, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Jean-Pierre",
                            Wedde = 1700m
                        },
                        new
                        {
                            DocentId = 47,
                            CampusId = 1,
                            Familienaam = "Berton",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Albert",
                            Wedde = 2100m
                        },
                        new
                        {
                            DocentId = 48,
                            CampusId = 6,
                            Familienaam = "Beths",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Frans ",
                            Wedde = 1600m
                        },
                        new
                        {
                            DocentId = 49,
                            CampusId = 3,
                            Familienaam = "Beyens",
                            InDienst = new DateTime(2019, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "René",
                            Wedde = 1300m
                        },
                        new
                        {
                            DocentId = 50,
                            CampusId = 1,
                            Familienaam = "Beyssens",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Herman",
                            Wedde = 1700m
                        },
                        new
                        {
                            DocentId = 51,
                            CampusId = 2,
                            Familienaam = "Billiet",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Albert",
                            Wedde = 1200m
                        },
                        new
                        {
                            DocentId = 52,
                            CampusId = 6,
                            Familienaam = "Billiet",
                            InDienst = new DateTime(2019, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Hector",
                            Wedde = 1600m
                        },
                        new
                        {
                            DocentId = 53,
                            CampusId = 5,
                            Familienaam = "Blavier",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Marcel",
                            Wedde = 2000m
                        },
                        new
                        {
                            DocentId = 54,
                            CampusId = 5,
                            Familienaam = " Blockx",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Roger",
                            Wedde = 1500m
                        },
                        new
                        {
                            DocentId = 55,
                            CampusId = 3,
                            Familienaam = "Blomme",
                            InDienst = new DateTime(2019, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Maurice",
                            Wedde = 1900m
                        },
                        new
                        {
                            DocentId = 56,
                            CampusId = 6,
                            Familienaam = "Bocklandt",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Willy",
                            Wedde = 1600m
                        },
                        new
                        {
                            DocentId = 57,
                            CampusId = 1,
                            Familienaam = "Bodart",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Emile",
                            Wedde = 1100m
                        },
                        new
                        {
                            DocentId = 58,
                            CampusId = 5,
                            Familienaam = "Boekaerts",
                            InDienst = new DateTime(2019, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Alfons",
                            Wedde = 1500m
                        },
                        new
                        {
                            DocentId = 59,
                            CampusId = 3,
                            Familienaam = "Bogaert",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Cesar",
                            Wedde = 1900m
                        },
                        new
                        {
                            DocentId = 60,
                            CampusId = 4,
                            Familienaam = "Bogaert",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Jan",
                            Wedde = 1400m
                        },
                        new
                        {
                            DocentId = 61,
                            CampusId = 2,
                            Familienaam = "Bogaerts",
                            InDienst = new DateTime(2019, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Jean",
                            Wedde = 1800m
                        },
                        new
                        {
                            DocentId = 62,
                            CampusId = 2,
                            Familienaam = "Bonduel",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Frans",
                            Wedde = 2200m
                        },
                        new
                        {
                            DocentId = 63,
                            CampusId = 5,
                            Familienaam = "Boonen",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Tom",
                            Wedde = 1000m
                        },
                        new
                        {
                            DocentId = 64,
                            CampusId = 4,
                            Familienaam = " Boons",
                            InDienst = new DateTime(2019, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Jozef",
                            Wedde = 1400m
                        },
                        new
                        {
                            DocentId = 65,
                            CampusId = 2,
                            Familienaam = "Borra",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Gabriel",
                            Wedde = 1800m
                        },
                        new
                        {
                            DocentId = 66,
                            CampusId = 3,
                            Familienaam = "Bosmans",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Joseph",
                            Wedde = 1300m
                        },
                        new
                        {
                            DocentId = 67,
                            CampusId = 1,
                            Familienaam = "Boucquet",
                            InDienst = new DateTime(2019, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Walter",
                            Wedde = 1700m
                        },
                        new
                        {
                            DocentId = 68,
                            CampusId = 1,
                            Familienaam = "Boumon",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Marcel",
                            Wedde = 2100m
                        },
                        new
                        {
                            DocentId = 69,
                            CampusId = 6,
                            Familienaam = "Bracke",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Ferdinand",
                            Wedde = 1600m
                        },
                        new
                        {
                            DocentId = 70,
                            CampusId = 3,
                            Familienaam = "Braeckeveldt",
                            InDienst = new DateTime(2019, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Adolphe",
                            Wedde = 1300m
                        },
                        new
                        {
                            DocentId = 71,
                            CampusId = 1,
                            Familienaam = "Braekevelt",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Omer",
                            Wedde = 1700m
                        },
                        new
                        {
                            DocentId = 72,
                            CampusId = 2,
                            Familienaam = "Brands",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Frans",
                            Wedde = 1200m
                        },
                        new
                        {
                            DocentId = 73,
                            CampusId = 6,
                            Familienaam = "Brankart",
                            InDienst = new DateTime(2019, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Jean",
                            Wedde = 1600m
                        },
                        new
                        {
                            DocentId = 74,
                            CampusId = 5,
                            Familienaam = "Brichard",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Emile",
                            Wedde = 2000m
                        },
                        new
                        {
                            DocentId = 75,
                            CampusId = 5,
                            Familienaam = "Brosteaux",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Georges",
                            Wedde = 1500m
                        },
                        new
                        {
                            DocentId = 76,
                            CampusId = 3,
                            Familienaam = "Bruneau",
                            InDienst = new DateTime(2019, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Emile",
                            Wedde = 1900m
                        },
                        new
                        {
                            DocentId = 77,
                            CampusId = 6,
                            Familienaam = "Bruyère",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Jean-Marie",
                            Wedde = 1600m
                        },
                        new
                        {
                            DocentId = 78,
                            CampusId = 1,
                            Familienaam = "Bruyere",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Joseph",
                            Wedde = 1100m
                        },
                        new
                        {
                            DocentId = 79,
                            CampusId = 5,
                            Familienaam = "Bruylandts",
                            InDienst = new DateTime(2019, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Dave",
                            Wedde = 1500m
                        },
                        new
                        {
                            DocentId = 80,
                            CampusId = 3,
                            Familienaam = "Bruyneel",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Johan",
                            Wedde = 1900m
                        },
                        new
                        {
                            DocentId = 81,
                            CampusId = 4,
                            Familienaam = "Buysse",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Lucien",
                            Wedde = 1400m
                        },
                        new
                        {
                            DocentId = 82,
                            CampusId = 2,
                            Familienaam = "Brandt",
                            InDienst = new DateTime(2019, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Christophe",
                            Wedde = 1800m
                        },
                        new
                        {
                            DocentId = 83,
                            CampusId = 2,
                            Familienaam = "Callens",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Norbert",
                            Wedde = 2200m
                        },
                        new
                        {
                            DocentId = 84,
                            CampusId = 5,
                            Familienaam = "Capiot",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Johan ",
                            Wedde = 1000m
                        },
                        new
                        {
                            DocentId = 85,
                            CampusId = 4,
                            Familienaam = "Cerami",
                            InDienst = new DateTime(2019, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Pino",
                            Wedde = 1400m
                        },
                        new
                        {
                            DocentId = 86,
                            CampusId = 2,
                            Familienaam = "Christiaens",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Georges",
                            Wedde = 1800m
                        },
                        new
                        {
                            DocentId = 87,
                            CampusId = 3,
                            Familienaam = "Claes",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Georges",
                            Wedde = 1300m
                        },
                        new
                        {
                            DocentId = 88,
                            CampusId = 1,
                            Familienaam = "Clerckx",
                            InDienst = new DateTime(2019, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Karel",
                            Wedde = 1700m
                        },
                        new
                        {
                            DocentId = 89,
                            CampusId = 1,
                            Familienaam = "Close",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Alex",
                            Wedde = 2100m
                        },
                        new
                        {
                            DocentId = 90,
                            CampusId = 6,
                            Familienaam = "Corbusier",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Yvan",
                            Wedde = 1600m
                        },
                        new
                        {
                            DocentId = 91,
                            CampusId = 3,
                            Familienaam = "Couvreur",
                            InDienst = new DateTime(2019, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Hilaire",
                            Wedde = 1300m
                        },
                        new
                        {
                            DocentId = 92,
                            CampusId = 1,
                            Familienaam = "Cretskens",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Wilfried",
                            Wedde = 1700m
                        },
                        new
                        {
                            DocentId = 93,
                            CampusId = 2,
                            Familienaam = "Criquielion",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Claude",
                            Wedde = 1200m
                        },
                        new
                        {
                            DocentId = 94,
                            CampusId = 6,
                            Familienaam = "Daems",
                            InDienst = new DateTime(2019, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Emile",
                            Wedde = 1600m
                        },
                        new
                        {
                            DocentId = 95,
                            CampusId = 5,
                            Familienaam = "Danneels",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Gustave",
                            Wedde = 2000m
                        },
                        new
                        {
                            DocentId = 96,
                            CampusId = 5,
                            Familienaam = "De Bruyne",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Fred",
                            Wedde = 1500m
                        },
                        new
                        {
                            DocentId = 97,
                            CampusId = 3,
                            Familienaam = "Decabooter",
                            InDienst = new DateTime(2019, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Arthur",
                            Wedde = 1900m
                        },
                        new
                        {
                            DocentId = 98,
                            CampusId = 6,
                            Familienaam = "De Clerq",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Hans",
                            Wedde = 1600m
                        },
                        new
                        {
                            DocentId = 99,
                            CampusId = 1,
                            Familienaam = "Decock",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Roger",
                            Wedde = 1100m
                        },
                        new
                        {
                            DocentId = 100,
                            CampusId = 5,
                            Familienaam = "Decraeye",
                            InDienst = new DateTime(2019, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Georges",
                            Wedde = 1500m
                        },
                        new
                        {
                            DocentId = 101,
                            CampusId = 3,
                            Familienaam = "Defraeye",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Odiel",
                            Wedde = 1900m
                        },
                        new
                        {
                            DocentId = 102,
                            CampusId = 4,
                            Familienaam = "De Jonghe",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Albert",
                            Wedde = 1400m
                        },
                        new
                        {
                            DocentId = 103,
                            CampusId = 2,
                            Familienaam = "Delbecque",
                            InDienst = new DateTime(2019, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Julien",
                            Wedde = 1800m
                        },
                        new
                        {
                            DocentId = 104,
                            CampusId = 2,
                            Familienaam = "Deloor",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Alfons",
                            Wedde = 2200m
                        },
                        new
                        {
                            DocentId = 105,
                            CampusId = 5,
                            Familienaam = "Deloor",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Gustaaf",
                            Wedde = 1000m
                        },
                        new
                        {
                            DocentId = 106,
                            CampusId = 4,
                            Familienaam = "Deltour",
                            InDienst = new DateTime(2019, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Hubert",
                            Wedde = 1400m
                        },
                        new
                        {
                            DocentId = 107,
                            CampusId = 2,
                            Familienaam = "Deman",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Paul",
                            Wedde = 1800m
                        },
                        new
                        {
                            DocentId = 108,
                            CampusId = 3,
                            Familienaam = "Demeyer",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Marc",
                            Wedde = 1300m
                        },
                        new
                        {
                            DocentId = 109,
                            CampusId = 1,
                            Familienaam = "De Mulder",
                            InDienst = new DateTime(2019, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Frans",
                            Wedde = 1700m
                        },
                        new
                        {
                            DocentId = 110,
                            CampusId = 1,
                            Familienaam = "De Muynck",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Johan",
                            Wedde = 2100m
                        },
                        new
                        {
                            DocentId = 111,
                            CampusId = 6,
                            Familienaam = "De muysere",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Jef",
                            Wedde = 1600m
                        },
                        new
                        {
                            DocentId = 112,
                            CampusId = 3,
                            Familienaam = "Depoorter",
                            InDienst = new DateTime(2019, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Jules",
                            Wedde = 1300m
                        },
                        new
                        {
                            DocentId = 113,
                            CampusId = 1,
                            Familienaam = "Depoorter",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Richard",
                            Wedde = 1700m
                        },
                        new
                        {
                            DocentId = 114,
                            CampusId = 2,
                            Familienaam = "Depredomme",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Prosper",
                            Wedde = 1200m
                        },
                        new
                        {
                            DocentId = 115,
                            CampusId = 6,
                            Familienaam = "Derboven",
                            InDienst = new DateTime(2019, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Willy",
                            Wedde = 1600m
                        },
                        new
                        {
                            DocentId = 116,
                            CampusId = 5,
                            Familienaam = "Derijcke",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Germain",
                            Wedde = 2000m
                        },
                        new
                        {
                            DocentId = 117,
                            CampusId = 5,
                            Familienaam = "Dernies",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Michel",
                            Wedde = 1500m
                        },
                        new
                        {
                            DocentId = 118,
                            CampusId = 3,
                            Familienaam = "Deruyter",
                            InDienst = new DateTime(2019, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Charles",
                            Wedde = 1900m
                        },
                        new
                        {
                            DocentId = 119,
                            CampusId = 6,
                            Familienaam = "Desimpelaere",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Maurice",
                            Wedde = 1600m
                        },
                        new
                        {
                            DocentId = 120,
                            CampusId = 1,
                            Familienaam = "Desmet",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Gilbert",
                            Wedde = 1100m
                        },
                        new
                        {
                            DocentId = 121,
                            CampusId = 5,
                            Familienaam = "Desplenter",
                            InDienst = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Georges",
                            Wedde = 1500m
                        },
                        new
                        {
                            DocentId = 122,
                            CampusId = 3,
                            Familienaam = "Despontin",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Léon",
                            Wedde = 1900m
                        },
                        new
                        {
                            DocentId = 123,
                            CampusId = 4,
                            Familienaam = "De Vlaeminck",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Eric",
                            Wedde = 1400m
                        },
                        new
                        {
                            DocentId = 124,
                            CampusId = 2,
                            Familienaam = "De Vlaeminck",
                            InDienst = new DateTime(2019, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Roger",
                            Wedde = 1800m
                        },
                        new
                        {
                            DocentId = 125,
                            CampusId = 2,
                            Familienaam = "Devolder",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Stijn",
                            Wedde = 2200m
                        },
                        new
                        {
                            DocentId = 126,
                            CampusId = 5,
                            Familienaam = "Dewaele",
                            HeeftRijbewijs = false,
                            InDienst = new DateTime(2019, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Maurice",
                            Wedde = 1000m
                        },
                        new
                        {
                            DocentId = 127,
                            CampusId = 4,
                            Familienaam = "De Wolf",
                            InDienst = new DateTime(2019, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Alfons",
                            Wedde = 1400m
                        },
                        new
                        {
                            DocentId = 128,
                            CampusId = 2,
                            Familienaam = "Dhaenens",
                            HeeftRijbewijs = true,
                            InDienst = new DateTime(2019, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voornaam = "Rudy",
                            Wedde = 1800m
                        });
                });

            modelBuilder.Entity("Model.Entities.Land", b =>
                {
                    b.Property<string>("LandCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LandCode");

                    b.ToTable("Landen");

                    b.HasData(
                        new
                        {
                            LandCode = "BE",
                            Naam = "België"
                        },
                        new
                        {
                            LandCode = "NL",
                            Naam = "Nederland"
                        },
                        new
                        {
                            LandCode = "DE",
                            Naam = "Duitsland"
                        },
                        new
                        {
                            LandCode = "FR",
                            Naam = "Frankrijk"
                        },
                        new
                        {
                            LandCode = "IT",
                            Naam = "Italië"
                        },
                        new
                        {
                            LandCode = "LU",
                            Naam = "Luxemburg"
                        });
                });

            modelBuilder.Entity("Model.Entities.Docent", b =>
                {
                    b.HasOne("Model.Entities.Campus", "Campus")
                        .WithMany("Docenten")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entities.Land", "Land")
                        .WithMany("Docenten")
                        .HasForeignKey("LandCode");
                });
#pragma warning restore 612, 618
        }
    }
}
